<div id="salesmanSearchHomeChild" class="subcontainer trigger">
    <div class="title">
        <span class="name">Busqueda de vendedores</span>
        <span>
            <img id="openSearchFilter" src="<?php echo $this->baseUrl() ?>/images/icons/search.gif" 
                alt="Buscar" class="cursorPointer" title="Buscar-Haz click aqui para modificar los criterios de busqueda" /></span>
    </div>
    <div class="body">
        <div id="salesmanSearchMenu" class="jqmWindow">
            <?php echo $this->searchForm ?>
        </div>
        <div id="salesmanSearchResult">
        </div>
    </div>
</div>
