<?php echo '<?xml version="1.0" encoding="ISO-8859-1"?>' ?>
<table>
    <metadata>
        <title><?php echo $this->fileName ?></title>
        <id>clientAdminTable</id>
    </metadata>
    <headers>
        <header type="string" value="Nombre" />
        <header type="string" value="Apellido" />
        <header type="string" value="Email" />
        <header type="string" value="Telefono" />
        <header type="string" value="Detalles" />
    </headers>
    <rows>
        <?php foreach ($this->salesmans as $salesman): ?>
            <row>
                <header value="<?php echo $salesman->first_name ?>" />
                <header value="<?php echo $salesman->last_name ?>" />
                <header value="<?php echo $salesman->email ?>" />
                <header value="<?php echo $salesman->telephone ?>" />
                <?php
                    $details = '';
                    $details .= '<img id="salesman' . $salesman->id . '" '
                        . 'src="' . $this->baseUrl() . '/images/icons/user.gif"  '
                        . 'class="viewSalesman cursorPointer" '
                        .'title="Detalle-Haz click para ver los detalles del vendedor" />';    
                ?>
                <header value="<?php echo $this->escape($details) ?>" class="encoded" />
            </row>
        <?php endforeach ?>
    </rows>
</table>
