<div id="pricelistChild" class="subcontainer trigger">
    <div class="title">
        <span class="name">Administracion de listas de precios</span>
    </div>
    <div class="body">
        <div id="pricelistUpload">
            <?php echo $this->form ?>
            <iframe id="uploadIfrm" name="uploadIfrm">
            </iframe>
        </div>
        <div id="pricelistFormContainer" class="hidden">
            <?php echo $this->pricelistForm ?>
        </div>
        <div id="pricelistShow">
        </div>
    </div>
</div>
