<img src="<?php echo $this->baseUrl() ?>/images/logo-small.png" 
     alt="Tipo de imagen no soportada" 
     class="main-logo" />
<div class="menu-container"></div>
<div class="session-info">
    <ul>
        <li><span class="label-title">Tipo de usuario:</span><?php echo $this->userType ?></li>
        <li><span class="label-title">Nombre:</span><?php echo $this->userName ?></li>
        <li><span class="label-title">Ambiente:</span><?php echo $this->environment ?></li>
        <li><span class="label-title">Version:</span><?php echo $this->version ?></li>
    </ul>
</div>   
