<div id="catalogsChild" class="subcontainer trigger">
    <div class="title">
        <span class="name">Administracion de catalogos de la applicacion</span>
    </div>
    <div class="body">
        <fieldset id="pricelistCategoryContainer">
            <legend>Categorias de listas de precios</legend>
            <div id="pricelistCategory"></div>
            <?php echo $this->pricelistCategoryForm ?>
            <input id="showAddPricelistCategory" type="button" value="Agregar categoria" class="button buttonSizeBig" />
        </fieldset>
    </div>
</div>
