<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/blueprint/screen.css" type="text/css"
              media="screen, projection" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/blueprint/print.css" type="text/css"
              media="print" />
        <!--[if IE ]>
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/blueprint/ie.css" type="text/css" media="screen, projection">
        <![endif]-->
        <link href="<?php echo $this->baseUrl() ?>/css/menu.css" rel="stylesheet" type="text/css" />
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/images/favicon.ico" type=
              "image/x-icon" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/tablesorter/style.css" type="text/css" media="print, projection, screen" />
        <link href="<?php echo $this->baseUrl() ?>/css/jqModal.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->baseUrl() ?>/css/jquery.tooltip.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="<?php echo $this->baseUrl() ?>/css/base.css" type="text/css" media=
              "screen, projection" />
              <?php echo $this->headScript(); ?>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jQuery.jCache.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/plugins.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.json-1.3.js" type="text/javascript"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.corner.src.js"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.hoverIntent.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.form.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jqModal.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-tooltip/jquery.tooltip.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery.xslt.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-validate/jquery.validate.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-validate/additional-methods.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/jquery-validate/localization/messages_es.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/tablesorter/addons/pager/jquery.tablesorter.pager.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/jquery/tablesorter/jquery.tablesorter.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/utils.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/loginHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/logoutHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/massUploadHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/clientSearchHomeHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/clientAddHomeHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/salesmanAddHomeHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/salesmanSearchHomeHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/pricelistHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/catalogsHandler.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/events.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/service.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/alerts.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() ?>/js/base.js" type="text/javascript"></script>
        <script src="<?php echo $this->url(array('controller' => 'javascript', 'action' => 'options')) ?>" type="text/javascript"></script>
    </head>
    <body>
        <div class="header-container"><?php echo $this->action('headerbar', 'common') ?></div>
        <div id="container" class="workarea-container"><?php echo $this->layout()->content ?></div>
        <div class="footer-container"><?php echo $this->partial('footer.phtml') ?></div>
        <div id="processStatusContainer"><span class="process-label">Procesando</span><span class="process-status"></span></div>
        <?php echo $this->partial('overlays.phtml') ?>
    </body>
</html>

