<div id="jqmContainer">
    <div id="defaultJQMWindow" class="jqmWindow">
        <div class="title">
            <span class="name"></span>
            <span class="close">
                <img src="<?php echo $this->baseUrl() ?>/images/icons/x.gif" alt="close" />
            </span>
        </div>
        <div class="body">
        </div>
        <div class="controls">
            <input type="button" class="button buttonSizeMedium accept"  value="Aceptar" />
            <input type="button" class="button buttonSizeMedium alert close" value="OK, Gracias!" />
            <input type="button" class="button buttonSizeMedium cancel close" value="Cancelar" />
        </div>
    </div>
</div>
