<div id="massUploadChild" class="subcontainer trigger">
    <div class="title">
        <span class="name">Carga en masa de clientes</span>
    </div>
    <div class="body">
        <div id="massuploadForm">
            <?php echo $this->form ?>
            <iframe id="uploadIfrm" name="uploadIfrm">
            </iframe>
        </div>
        <div id="massuploadResult">
        </div>
    </div>
</div>
