<div id="clientAddHomeChild" class="subcontainer trigger">
    <div class="title">
        <span class="name">Agregar cliente</span>
    </div>
    <div class="body">
        <div id="messageArea">
            <p>Para agregar un cliente al menos necesitas:
                <ol>
                    <li>Agregar informacion básica del contacto como lo es un correo electronico y/o telefono</li>
                    <li>Seleccionar como quieres que el vendedor sea asignado</li>
                </ol>
            <p>
            <input id="addClient" type="button" class="button buttonSizeMedium" 
                value="Agregar" title="Haz click aqui para agregar un cliente nuevo" />
        </div>
        <div id="formArea">
            <?php echo $this->form ?>
            <div id="displayFormControls"></div>
        </div>
    </div>
</div>
